// Code generated by mockery. DO NOT EDIT.

package git

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CloneAtCommit provides a mock function with given fields: url, commit
func (_m *MockClient) CloneAtCommit(url string, commit string) (fs.FS, error) {
	ret := _m.Called(url, commit)

	if len(ret) == 0 {
		panic("no return value specified for CloneAtCommit")
	}

	var r0 fs.FS
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (fs.FS, error)); ok {
		return rf(url, commit)
	}
	if rf, ok := ret.Get(0).(func(string, string) fs.FS); ok {
		r0 = rf(url, commit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, commit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CloneAtCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloneAtCommit'
type MockClient_CloneAtCommit_Call struct {
	*mock.Call
}

// CloneAtCommit is a helper method to define mock.On call
//   - url string
//   - commit string
func (_e *MockClient_Expecter) CloneAtCommit(url interface{}, commit interface{}) *MockClient_CloneAtCommit_Call {
	return &MockClient_CloneAtCommit_Call{Call: _e.mock.On("CloneAtCommit", url, commit)}
}

func (_c *MockClient_CloneAtCommit_Call) Run(run func(url string, commit string)) *MockClient_CloneAtCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClient_CloneAtCommit_Call) Return(_a0 fs.FS, _a1 error) *MockClient_CloneAtCommit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CloneAtCommit_Call) RunAndReturn(run func(string, string) (fs.FS, error)) *MockClient_CloneAtCommit_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestCommit provides a mock function with given fields: url
func (_m *MockClient) GetLatestCommit(url string) (string, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCommit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetLatestCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCommit'
type MockClient_GetLatestCommit_Call struct {
	*mock.Call
}

// GetLatestCommit is a helper method to define mock.On call
//   - url string
func (_e *MockClient_Expecter) GetLatestCommit(url interface{}) *MockClient_GetLatestCommit_Call {
	return &MockClient_GetLatestCommit_Call{Call: _e.mock.On("GetLatestCommit", url)}
}

func (_c *MockClient_GetLatestCommit_Call) Run(run func(url string)) *MockClient_GetLatestCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_GetLatestCommit_Call) Return(_a0 string, _a1 error) *MockClient_GetLatestCommit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetLatestCommit_Call) RunAndReturn(run func(string) (string, error)) *MockClient_GetLatestCommit_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestRelease provides a mock function with given fields: url
func (_m *MockClient) GetLatestRelease(url string) (string, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRelease")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetLatestRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRelease'
type MockClient_GetLatestRelease_Call struct {
	*mock.Call
}

// GetLatestRelease is a helper method to define mock.On call
//   - url string
func (_e *MockClient_Expecter) GetLatestRelease(url interface{}) *MockClient_GetLatestRelease_Call {
	return &MockClient_GetLatestRelease_Call{Call: _e.mock.On("GetLatestRelease", url)}
}

func (_c *MockClient_GetLatestRelease_Call) Run(run func(url string)) *MockClient_GetLatestRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_GetLatestRelease_Call) Return(_a0 string, _a1 error) *MockClient_GetLatestRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetLatestRelease_Call) RunAndReturn(run func(string) (string, error)) *MockClient_GetLatestRelease_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
