with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
structname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
disable-version-string: True
packages:
  github.com/nicjohnson145/plantr/internal/controller:
    interfaces:
      GitClient:
      StorageClient:
