// Code generated by mockery. DO NOT EDIT.

package controller

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVaultClient is an autogenerated mock type for the VaultClient type
type MockVaultClient struct {
	mock.Mock
}

type MockVaultClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVaultClient) EXPECT() *MockVaultClient_Expecter {
	return &MockVaultClient_Expecter{mock: &_m.Mock}
}

// ReadSecretData provides a mock function with given fields: ctx
func (_m *MockVaultClient) ReadSecretData(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadSecretData")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVaultClient_ReadSecretData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadSecretData'
type MockVaultClient_ReadSecretData_Call struct {
	*mock.Call
}

// ReadSecretData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVaultClient_Expecter) ReadSecretData(ctx interface{}) *MockVaultClient_ReadSecretData_Call {
	return &MockVaultClient_ReadSecretData_Call{Call: _e.mock.On("ReadSecretData", ctx)}
}

func (_c *MockVaultClient_ReadSecretData_Call) Run(run func(ctx context.Context)) *MockVaultClient_ReadSecretData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockVaultClient_ReadSecretData_Call) Return(_a0 map[string]interface{}, _a1 error) *MockVaultClient_ReadSecretData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVaultClient_ReadSecretData_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockVaultClient_ReadSecretData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVaultClient creates a new instance of MockVaultClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVaultClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVaultClient {
	mock := &MockVaultClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
